---
# package-msmtp tasks main file

- name: Explicitly update repositories cache
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - msmtp
      - msmtp-mta
      - mailutils

- name: Template config file
  become: true
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    force: yes
    backup: true
    owner: root
    group: root
    mode: "0600"

- name: Template aliases file
  become: true
  ansible.builtin.template:
    src: msmtp.aliases.j2
    dest: /etc/msmtp.aliases
    force: yes
    backup: true
    owner: root
    group: root
    mode: "0600"
