---
# zabbix-agent-smartmontools tasks main file

# Attribution:
# Some files were pulled from zbx-smartctl project created by
# Vitaly Zhuravlev and are licensed on GPL v3 terms.
# <https://github.com/v-zhuravlev/zbx-smartctl>
#

- name: Configure user parameters
  become: true
  ansible.builtin.copy:
    src: zabbix_smartctl.conf
    dest: /etc/zabbix/zabbix_agentd.d/zabbix_smartctl.conf
    force: yes
    backup: false
    owner: root
    group: zabbix
    mode: "0440"
  register: copy_userparams_result

- name: Configure sudo
  become: true
  ansible.builtin.copy:
    src: sudoers_zabbix_smartctl
    dest: /etc/sudoers.d/sudoers_zabbix_smartctl
    force: yes
    backup: false
    owner: root
    group: root
    mode: "0440"

- name: Create scripts directory
  become: true
  ansible.builtin.file:
    path: /etc/zabbix/scripts
    state: directory
    owner: root
    group: zabbix
    mode: "0750"

- name: Copy discovery script file
  become: true
  ansible.builtin.copy:
    src: smartctl-disks-discovery.pl
    dest: /etc/zabbix/scripts/{{ item }}
    force: yes
    backup: false
    owner: root
    group: zabbix
    mode: "0750"
  register: copy_script_result

- name: Restart zabbix-agent
  when: copy_userparams_result.changed or copy_script_result.changed
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
