---
# system-reboot tasks main file

- name: Reboot system
  when: allow_reboot
  become: true
  ansible.builtin.reboot:
    post_reboot_delay: 0
  register: reboot_result

- name: Update host facts
  when: reboot_result.changed
  become: false
  ansible.builtin.set_fact:
    reboot_successfull: "{{ True if reboot_result.rebooted == true else False }}"
