---
# packages-upgrade tasks main file

- name: Explicitly update repositories cache
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Upgrade all installed packages
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    upgrade: "yes"
  register: packages_upgrade_result

- name: Set host facts
  become: false
  ansible.builtin.set_fact:
    packages_upgrade_summary: "{{ (packages_upgrade_result.stdout_lines | select('search', 'upgraded,'))[0] }}"
