---
# ufw tasks main file

- name: Explicitly update repositories cache
  become: true
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Install package
  become: true
  apt:
    name:
      - ufw

- name: Disable IPV6 support
  become: true
  lineinfile:
    path: /etc/default/ufw
    create: no
    regexp: "^IPV6="
    line: IPV6=no

- name: Set default incoming policy
  become: true
  command: "ufw default deny incoming"

- name: Set default outgoing policy
  become: true
  command: "ufw default allow outgoing"

- name: Set default routed policy
  become: true
  command: "ufw default deny routed"

- name: Allow SSH connections
  become: true
  command: "ufw allow ssh"

- name: Enable UFW
  become: true
  shell: "ufw --force enable"
