---
# package-lynis tasks main file

- name: Explicitly update repositories cache
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Install package
  become: true
  ansible.builtin.apt:
    name:
      - lynis

- name: Copy configuration file
  become: true
  ansible.builtin.copy:
    src: custom.prf
    dest: /etc/lynis/custom.prf
    force: yes
    backup: true
    owner: root
    group: root
    mode: "0644"
  