---
# example-netplan tasks main file

- name: Copy configuration file examples
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/netplan/{{ item }}.example
    force: yes
    backup: false
    owner: root
    group: root
    mode: "0644"
  loop: [bond-dhcp.yaml, bond-static.yaml, dhcp.yaml, static.yaml]
