---
# hardening-firewall tasks main file

- name: Explicitly update repositories cache
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Install package
  become: true
  ansible.builtin.apt:
    name:
      - ufw

- name: Disable IPV6 support
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    create: no
    regexp: "^IPV6="
    line: IPV6=no

- name: Set default incoming policy
  become: true
  ansible.builtin.command: "/usr/sbin/ufw default deny incoming"

- name: Set default outgoing policy
  become: true
  ansible.builtin.command: "/usr/sbin/ufw default allow outgoing"

- name: Set default routed policy
  become: true
  ansible.builtin.command: "/usr/sbin/ufw default deny routed"

- name: Allow SSH connections
  become: true
  ansible.builtin.command: "/usr/sbin/ufw allow in to any port {{ ufw_ssh_port }} proto tcp"

- name: Enable UFW
  become: true
  ansible.builtin.shell: "/usr/sbin/ufw --force enable"
