---
# timedate tasks main file

- name: Check current time zone
  become: false
  shell: timedatectl show -p Timezone | cut -d "=" -f 2
  changed_when: False
  register: timedate_timezone_current

- name: Set time zone
  when: timedate_timezone_current.stdout != timedate_timezone
  become: true
  command: timedatectl set-timezone {{ timedate_timezone }}

- name: Enable and start systemd-timesyncd service
  when: ansible_virtualization_type != "lxc"
  become: true
  service:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Check network time synchronization status
  become: true
  shell: timedatectl show -p NTP | cut -d "=" -f 2
  changed_when: False
  register: timedate_ntp_status

- name: Activate network time synchronization
  when: (ansible_virtualization_type != "lxc") and (timedate_ntp_status.stdout == "no")
  become: true
  command: timedatectl set-ntp true
