---
# package-needrestart tasks main file

- name: Explicitly update repositories cache
  become: true
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Install packages
  become: true
  apt:
    name:
      - libpam-systemd
      - needrestart
