---
# package-zfsutils-linux tasks main file

- name: Explicitly update repositories cache
  become: true
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes

- name: Install package
  become: true
  ansible.builtin.apt:
    name:
      - zfsutils-linux

- name: Copy cron configuration file
  become: true
  ansible.builtin.copy:
    src: zfsutils-linux
    dest: /etc/cron.d/zfsutils-linux
    force: yes
    backup: false
    owner: root
    group: root
    mode: "0644"
  